if(window.self!==window.top){function gameInstancePostRun(){gameInstance.Module.postRun.push(function(){gameInstance.logo.style.display=gameInstance.progress.style.display="none";gameInstance.container.firstChild.style.visibility="hidden";var loadingBox=document.getElementById('loading-box');gameInstance.container.firstChild.style.visibility="visible";loadingBox.remove();var fullscreenBtn=document.querySelector(".fullscreen");if(fullscreenBtn!==null){fullscreenBtn.style.visibility="visible";}
var bugBtn=document.querySelector(".bug");if(bugBtn!==null){bugBtn.style.visibility="visible";}
var installerBtn=document.getElementById("btn-installer");if(installerBtn!==null){installerBtn.style.visibility="visible";}
var categoryBtn=document.querySelector(".category");if(categoryBtn!==null){categoryBtn.style.visibility="visible";}});}
window.addEventListener("message",function(msg){if(msg.data.detail==="upsell"){var container=document.getElementById("webgl-content");container.insertAdjacentHTML("beforeend",msg.data.markup);var playNowButton=document.getElementById('play-now');if(playNowButton!==null){playNowButton.style.display="block";playNowButton.addEventListener('click',function(){invokeGame();playNowButton.style.display="none";if(gameInstance){gameInstancePostRun();}});}
var videoAnchor=container.querySelector("#up-sell a");videoAnchor.addEventListener("mouseover",function(){var theVideo=videoAnchor.querySelector('video');if(theVideo){theVideo.play();}});videoAnchor.addEventListener("mouseout",function(){var theVideo=videoAnchor.querySelector('video');if(theVideo){theVideo.pause();}});var playNowButton=document.getElementById('play-now');playNowButton.style.display="block";}
if(msg.data.detail==="show_pwa_button"){const butInstall=document.getElementById('btn-installer');if(butInstall&&msg.data.show===true){butInstall.classList.remove("hide");}}});window.parent.postMessage("upsellMarkup");window.parent.postMessage("showPWAButton");}
else{invokeGame();var GAscript=document.createElement('script');GAscript.src="https://www.googletagmanager.com/gtag/js?id=UA-11106352-23";document.head.appendChild(GAscript);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','UA-11106352-23',{'content_group1':'Gaming Traffic'});gtag('event','click',{'event_category':'Game Pageview Without Wrapper','event_label':window.location.href,'transport_type':'beacon','event_callback':function(){}});window.addEventListener('load',(event)=>{if(document.body.classList.contains('drift-hunters')){const delayAmount=2500;setTimeout(fnInitAdThriveAds,delayAmount);}});function fnInitAdThriveAds(){document.body.classList.add("ads-enabled");(function(w,d){w.adthrive=w.adthrive||{};w.adthrive.cmd=w.adthrive.cmd||[];w.adthrive.plugin='adthrive-ads-1.0.43-manual';w.adthrive.host='ads.adthrive.com';var s=d.createElement('script');s.async=!0;s.referrerpolicy='no-referrer-when-downgrade';s.src='https://'+w.adthrive.host+'/sites/5ba533eb02763b77649ff1ee/ads.min.js?referrer='+w.encodeURIComponent(w.location.href);var n=d.getElementsByTagName('script')[0];n.parentNode.insertBefore(s,n);})(window,document);fnPreventAdThriveAdRotation=function(){setInterval(function(){const pages=['/media/games/dh/index.html'];const adThriveLoaded=document.getElementsByTagName('body')[0].classList.contains('adthrive-device-phone')||document.getElementsByTagName('body')[0].classList.contains('adthrive-device-tablet')||document.getElementsByTagName('body')[0].classList.contains('adthrive-device-desktop');if(!adThriveLoaded){console.log('Waiting for AdThrive...')
return}
pages.forEach(item=>{if(window.location.pathname===item){window.adthrive.slotManager.updateRefreshTimeout(window.adthrive.slots.get(),0);console.log('Disable AdThrive ad rotation');}});},2000);}
if(document.body.classList.contains('disable-ad-rotation')){setTimeout(fnPreventAdThriveAdRotation,5000);}}}
function fnInitPWAAppInstaller(){let deferredPrompt;const butInstall=document.getElementById('btn-installer');butInstall.addEventListener('click',(e)=>{window.parent.postMessage("pwa-install");});}
